### ISSUE TITLE
Can pyvoronoi work with polygon?

### ISSUE THREAD

**Issue by minmingzhao** [fabanc/pyvoronoi#14]
Can it works with polygon? 
Such as middle of the image below https://www.boost.org/doc/libs/1_68_0/libs/polygon/doc/images/voronoi3.png
The voronoi vertices seems not correct. I put one segment as [[x0,y0],[x1,y1],[x2,y2],[x3,y3],..[xn,yn],[x0,y0]]
Thanks!

**Comment by fabanc** [comment]
Hi Minming,

It does not work with polygon as such, but it is possible to break down the polygons into simple lines (only two nodes), and send them to the Voronoi library.  Does it work if you try that?

**Comment by minmingzhao** [comment]
Hi Fabanc, 
Actually it works. I should have tried that before posting. :)
