### ISSUE TITLE
Bug. Vertex Positions are not corretly rounded.

### ISSUE THREAD

**Issue by jnthnw** [fabanc/pyvoronoi#37]
Bug: Position is not rounded but truncated when added to Points. This leads to deviation of positions, when floating errors occur.

**Comment by fabanc** [comment]
Thank you @jnthnw! I will try to reproduce and fix. I am letting C++ handle the conversion automatically. Have you noticed the issue for:

- Points passed to the pyvoronoi API?
- Point created as part of the Voronoi diagram output?
- Both?
